### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by ERnsTL** [shawhull/gling#2]
Greetings, thanks for creating a library for sending file descriptors over unix sockets! I would like to use this in a hobby project of mine.

Please add a license, like for example MIT in a file named ```LICENSE```.

Github has [a step-by-step how-to](https://help.github.com/articles/adding-a-license-to-a-repository/) for this.

**Comment by shawhull** [comment]
@ERnsTL 
Thanks for your great advice!!
I've created the `LICENSE`(MIT) file in this PR https://github.com/shawhull/gling/pull/3
